batch_size: 8
image:
    center_x: 288
    center_y: 249
    width: 360 # Larger window, contains full data plus a good amount
imagefolder: L:/FermiUN_TrainingData
imageprefix: bright_
learning_rate: 5.0e-06
max_epochs: 1000
model_path: ''
radius: 120
test_fraction: 0.1
testlist: []
trainlist: []
validation_fraction: 0.2
validationlist: []
